import os
from dotenv import load_dotenv

# Carga las variables del archivo .env
load_dotenv()

# 🤖 DATOS PRINCIPALES DEL BOT
BOT_TOKEN = os.getenv("BOT_TOKEN", "")
ADMIN_ID = int(os.getenv("ADMIN_ID", 0))
MONGO_URI = os.getenv("MONGO_URI", "")

# ℹ️ INFORMACIÓN GENERAL
VERSION = "4.0"
MIN_SERVICIOS = 200
MAX_SERVICIOS = 1500
CANAL_OBLIGATORIO = "@VoltixPro"

# 💰 MONEDA Y RECARGAS
SIMBOLO = "$"
MONTO_MINIMO = 5.0
PORCENTAJE_GANANCIA = 20.0

# 💳 MÉTODOS DE PAGO
METODO_PAGO = "Transferencia Bancaria / USDT"
DATOS_PAGO = "Sin configurar aún"
DIRECCION_USDT = ""
DIRECCION_BTC = ""

# 🔒 SEGURIDAD
CLAVE_SEGURIDAD_ADMIN = ""

# ⚙️ VALORES POR DEFECTO GENERALES
LIMITE_GASTO_DIARIO = 0
AVISO_SALDO_BAJO = 2.0
RECOMPENSA_REFERIDO = 5.0
